title: This is my brain...
description: Hey! - new year new me. Time to show off some of my hobby projects.
github_username: aduriseti

remote_theme: pages-themes/primer
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings