title: This is my brain...
description: Hey! - new year new me. Time to show off some of my hobby projects.
github_username: aduriseti

theme: minima

# Show previews on the homepage automatically
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings